[project]
name = "meow-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openrouter>=0.1.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "slack-bolt>=1.27.0",
    "slack-cli-hooks<1.0.0",
]
